### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by sandreza** [CliMA/Vizinanigans.jl#3]
Not sure exactly how we test plotting through CI, but we should have some kind of tests

**Comment by ali-ramadhan** [comment]
Yeah kinda hard to test for correctness but a simple test could be to just produce a png or mp4.

Would make sure package precompiles and the code can be run without errors.

**Comment by ali-ramadhan** [comment]
Actually I can open a PR that adds CI tests that just runs the examples.

GLMakie.jl might be tough to run on CI but maybe we can just use what GLMakie.jl came up with: https://github.com/JuliaPlots/GLMakie.jl/blob/master/.github/workflows/ci.yml

**Comment by sandreza** [comment]
Nice idea @ali-ramadhan! A pull request would be most welome :)
